"""Data models for brushless motor specifications."""

from dataclasses import dataclass, field, asdict
from typing import Optional


@dataclass
class MotorSpec:
    """Represents a brushless motor with all its specifications.

    Fields map directly to the Google Sheet columns.
    """

    ref: str = ""            # REF - unique reference code (e.g. "3BHO-0802-12000")
    marque: str = ""         # MARQUE - brand/manufacturer
    nom: str = ""            # NOM - motor name/series
    version: str = ""        # VERSION
    classe: str = ""         # CLASSE - stator class (e.g. "0802", "2207")
    kv: str = ""             # KV rating
    poids: str = ""          # POIDS - weight in grams
    h_stator: str = ""       # H STATOR - stator height (mm)
    d_stator: str = ""       # D STATOR - stator diameter (mm)
    h_moteur: str = ""       # H MOTEUR - motor height (mm)
    d_moteur: str = ""       # D MOTEUR - motor diameter (mm)
    d_shaft: str = ""        # D SHAFT - shaft diameter (mm)
    l_shaft: str = ""        # L SHAFT - shaft length (mm)
    type_shaft: str = ""     # TYPE SHAFT (Tige, etc.)
    vis_hel: str = ""        # VIS HEL - prop nut
    vis_fix: str = ""        # VIS FIX - mounting screws
    entraxe_fix: str = ""    # ENTRAXE FIX - mounting pattern (mm)
    lipo: str = ""           # LIPO - battery type (2S, 3S, 4S, 6S, etc.)
    voltage: str = ""        # VOLTAGE
    l_cable: str = ""        # L CABLE - cable length
    type_cable: str = ""     # TYPE CABLE - wire gauge
    helice: str = ""         # HELICE - propeller size
    puissance: str = ""      # PUISSANCE - power (W)
    amp: str = ""            # AMP - current (A)
    aimant: str = ""         # AIMANT - magnet type
    cloche: str = ""         # CLOCHE - bell type
    config: str = ""         # CONFIG - pole/stator configuration (e.g. 12N14P)
    lien: str = ""           # LIEN - product link
    img: str = ""            # IMG - image URL
    source_url: str = ""     # Internal: where data was scraped from

    def generate_ref(self) -> str:
        """Generate a reference code from brand, class and KV."""
        if not self.marque or not self.kv:
            return self.ref

        # Create brand prefix (first 4 chars uppercase)
        brand_prefix = self.marque[:4].upper().replace(" ", "")
        classe = self.classe or "0000"
        kv = self.kv

        self.ref = f"{brand_prefix}-{classe}-{kv}"
        return self.ref

    def to_sheet_row(self) -> list:
        """Convert motor specs to a row matching Google Sheet column order."""
        return [
            "",             # ID (auto-generated by sheet or left blank)
            self.ref,
            self.marque,
            self.nom,
            self.version,
            self.classe,
            self.kv,
            self.poids,
            self.h_stator,
            self.d_stator,
            self.h_moteur,
            self.d_moteur,
            self.d_shaft,
            self.l_shaft,
            self.type_shaft,
            self.vis_hel,
            self.vis_fix,
            self.entraxe_fix,
            self.lipo,
            self.voltage,
            self.l_cable,
            self.type_cable,
            self.helice,
            self.puissance,
            self.amp,
            self.aimant,
            self.cloche,
            self.config,
            self.lien,
            self.img,
        ]

    def is_valid(self) -> bool:
        """Check if the motor has enough data to be added to the catalog."""
        return bool(self.marque and self.kv and self.classe)

    def completeness_score(self) -> float:
        """Return a score 0-1 indicating how complete the specification is."""
        fields = [
            self.ref, self.marque, self.nom, self.classe, self.kv,
            self.poids, self.h_stator, self.d_stator, self.h_moteur,
            self.d_moteur, self.d_shaft, self.l_shaft, self.type_shaft,
            self.lipo, self.voltage, self.helice, self.lien, self.img,
        ]
        filled = sum(1 for f in fields if f)
        return filled / len(fields)

    def __eq__(self, other):
        if not isinstance(other, MotorSpec):
            return False
        return self.ref == other.ref

    def __hash__(self):
        return hash(self.ref)
